---
title: "Prediction Trees - Stat 452"
author: "Justin Cornejo Leon"
format: 
  html: 
   self-contained: TRUE
---

```{r}
library(rpart)
```

### a

```{r}
county_votes <- readRDS(url("https://ericwfox.github.io/data/county_votes16.rds"))

county_votes$result <- factor(county_votes$trump_win, levels = c(1,0), labels = c("trump", "clinton"))
```

### b

```{r}
set.seed(123)
train_index <- sample(1:nrow(county_votes), round(0.7 * nrow(county_votes)))
county_votes_train <- county_votes[train_index, ]
county_votes_test <- county_votes[-train_index, ]
```

### c

```{r}
t1 <- rpart(result ~ obama_pctvotes + pct_pop65 + pct_black + pct_white + pct_hispanic + pct_asian + highschool + bachelors + income, data = county_votes_train,method = "class")
```

### d

```{r}
par(cex=0.7, xpd=NA)
plot(t1)
text(t1, use.n = TRUE)
```

The most important predictor variable for predicting the election result in each county is obama_pctvotes. There are a total of 8 internal nodes and 10 terminal nodes.

### e

```{r}
preds <- predict(t1, newdata = county_votes_test, type = "class")
cm <- table(predicted = preds, actual = county_votes_test$result)
addmargins(cm)
```

accuracy

```{r}
(760 + 150) / 934
```

sensitivity

```{r}
760 / (760 + 11)
```

specificity

```{r}
150 / (150 + 13)
```
